export default [
  {
    _id: "A201",
    name: "HTML and CSS Basics",
    description: "Create a simple web page using HTML and CSS.",
    course: "RS101",
    dueDate: "2024-10-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A202",
    name: "Responsive Web Design",
    description:
      "Create a responsive web page using HTML, CSS, and JavaScript.",
    course: "RS101",
    dueDate: "2024-15-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A203",
    name: "JavaScript Fundamentals",
    description: "Create a simple web page using HTML, CSS, and JavaScript.",
    course: "RS101",
    dueDate: "2024-10-30T23:59",
    totalPoints: 100,
    availableFromDate: "2024-10-20T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A204",
    name: "Final Project: Complete Website",
    description: "Create a complete website using HTML, CSS, and JavaScript.",
    course: "RS101",
    dueDate: "2024-12-12T23:59",
    totalPoints: 200,
    availableFromDate: "2024-12-01T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A301",
    name: "Sorting Algorithm Analysis",
    description: "Implement and analyze sorting algorithms.",
    course: "RS102",
    dueDate: "2024-10-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A302",
    name: "Graph Algorithms Implementation",
    description: "Implement graph algorithms.",
    course: "RS102",
    dueDate: "2024-15-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A303",
    name: "Dynamic Programming Problems",
    description: "Solve dynamic programming problems.",
    course: "RS102",
    dueDate: "2024-10-30T23:59",
    totalPoints: 100,
    availableFromDate: "2024-10-20T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A304",
    name: "Final Exam: Algorithm Design",
    description: "Complete the final exam for the course.",
    course: "RS102",
    dueDate: "2024-12-12T23:59",
    totalPoints: 200,
    availableFromDate: "2024-12-01T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A401",
    name: "SQL Query Practice",
    description: "Practice writing SQL queries.",
    course: "RS103",
    dueDate: "2024-10-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A402",
    name: "Database Design Project",
    description: "Design a database for a specific application.",
    course: "RS103",
    dueDate: "2024-15-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A403",
    name: "NoSQL Database Implementation",
    description: "Implement a NoSQL database for a specific application.",
    course: "RS103",
    dueDate: "2024-10-30T23:59",
    totalPoints: 100,
    availableFromDate: "2024-10-20T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A404",
    name: "Final Exam: Database Systems",
    description: "Complete the final exam for the course.",
    course: "RS103",
    dueDate: "2024-12-12T23:59",
    totalPoints: 200,
    availableFromDate: "2024-12-01T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A501",
    name: "Functional Programming Exercises",
    description: "Complete functional programming exercises.",
    course: "RS104",
    dueDate: "2024-10-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A502",
    name: "Object-Oriented Design Patterns",
    description: "Implement object-oriented design patterns.",
    course: "RS104",
    dueDate: "2024-15-01T23:59",
    totalPoints: 100,
    availableFromDate: null,
    availableUntilDate: null,
    published: true,
  },
  {
    _id: "A503",
    name: "Logic Programming with Prolog",
    description: "Complete logic programming exercises.",
    course: "RS104",
    dueDate: "2024-10-30T23:59",
    totalPoints: 100,
    availableFromDate: "2024-10-20T00:00",
    availableUntilDate: null,
    published: false,
  },
  {
    _id: "A504",
    name: "Final Project: Concurrent Programming",
    description: "Complete a concurrent programming project.",
    course: "RS104",
    dueDate: "2024-12-12T23:59",
    totalPoints: 200,
    availableFromDate: "2024-12-01T00:00",
    availableUntilDate: null,
    published: false,
  },
];
